[package]
name = "tiled_wfc"
description = "A n-dimensional tiled wave function collapse library"
version = "0.4.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
nd_matrix = { path = "/Users/josh/projects/nd_matrix" }
rand = "0.8"
bitvec = "1"
