[package]
name = "tiled_wfc"
description = "A n-dimensional tiled wave function collapse library"
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
nd_matrix = "0.3.0"
rand = "0.8"
bitvec = "1"
